on:
  push:
  pull_request:
    branches:
      - main

name: PHPUnit Tests
jobs:
  runPHPUnitTests:
    name: Run PHPUnit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.2']
        wp-versions: ['latest']

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug
          tools: composer:v2
          extensions: mysqli, mbstring

      # Cache PHP extensions
      - name: Cache PHP extensions
        uses: actions/cache@v4
        with:
          path: /usr/local/lib/php/extensions
          key: ${{ runner.os }}-php-ext-${{ matrix.php-versions }}-${{ hashFiles('.github/workflows/phpunit.yml') }}

      # Get Composer cache directory
      - name: Get composer cache directory
        id: composercache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      # Cache Composer dependencies
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: "${{ runner.os }}-php-${{ matrix.php-versions }}-composer-${{ hashFiles('**/composer.lock') }}"
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-versions }}-composer-

      # Cache WordPress test suite
      - name: Cache WordPress test suite
        uses: actions/cache@v4
        with:
          path: /tmp/wordpress-tests-lib
          key: wp-tests-${{ matrix.wp-versions }}-${{ hashFiles('tests/install-wp-tests.sh') }}

      # Cache PHPUnit test results
      - name: Cache PHPUnit test results
        uses: actions/cache@v4
        with:
          path: .phpunit.result.cache
          key: phpunit-cache-${{ github.sha }}
          restore-keys: |
            phpunit-cache-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Install required system packages
        run: sudo apt-get update && sudo apt-get install -y subversion

      - name: Install WordPress Test Suite
        run: |
          if [ ! -d "/tmp/wordpress-tests-lib" ]; then
            bash tests/install-wp-tests.sh wordpress_test root root 127.0.0.1 ${{ matrix.wp-versions }}
          fi

      - name: Run Unit Tests
        run: composer run test:unit

      - name: Run Integration Tests
        run: composer run test:integration
